eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
    instance:
        hostname: localhost
        instance-id: ${spring.application.name}:${random.int}
server:

#  port: ${random.int(10000,[19999])} # 随机数
#    port: 1001

    port: 8101

spring:
    application:
        name: eureka-server